apiVersion: batch/v1
kind: Job
metadata:
  name: nlp-ticket-job
spec:
  template:
    spec:
      containers:
        - name: nlp-container
          image: my-nlp-pipeline:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 2
