apiVersion: batch/v1
kind: Job
metadata:
  name: nlp-ticket-job
spec:
  template:
    spec:
      containers:
        - name: nlp-container
          image: nlp-support-ticket-ml-pipeline:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: data-storage
            mountPath: /app/data
      restartPolicy: OnFailure
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: nlp-pvc


